<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Dipesh-PC" ignored="1" name="Default test(failed)" tests="2" failures="1" timestamp="2020-01-29T15:18:55 PST" time="0.156" errors="0">
  <testcase name="test2" time="0.018" classname="demo.TestNGRetryFailedTests_Demo"/>
  <testcase name="test3" time="0.007" classname="demo.TestNGRetryFailedTests_Demo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demo.TestNGRetryFailedTests_Demo.test3(TestNGRetryFailedTests_Demo.java:26)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.0" classname="demo.TestNGRetryFailedTests_Demo">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
